language: python
python: 3.6
branches: master

install:
    - pip install -r requirements.txt

script: true

before_deploy:
    - mkdocs build --verbose --clean --strict # Build a local version of the docs
    - echo "wiki.robonomics.network" > ./site/CNAME

deploy:
    provider: pages
    token: $github_token
    cleanup: false
    keep_history: true
    local_dir: site
    edge: true
    on:
        branch: master

