site_name: Robonomics wiki
nav:
  - "Getting Started": index.md
  - "R&D based on Robonomics Network": r_and_d.md
  - "Community": community.md
  - "Try it out":
    - "Get Weather on Fuji Mountain": try_it_out/get_weather_on_fuji_mountain.md
    - "Robonomics DApp Overview": try_it_out/robonomics_dapp_overview.md
    - "AIRA Installation on VirtualBox": try_it_out/aira_installation.md
    - "Interact With AIRA": try_it_out/interact_with_aira.md
  - Cases:
    - "Open Sensor Network Run by IPFS": cases/open_sensor_network_run_by_ipfs.md
    - "Create Digital Identity Run by Ethereum": cases/digital_identity.md
    # - "Offset Electricity Consumption Rub by Ethereum": cases/offset_electricity_consumption_run_by_ethereum.md
    # - "Run by Substrate": cases/substrate_demo.md
  - Learn:
    - "AIRA":
      - Overview: aira/overview.md
      - Installation: aira/installation.md
      - "Basic Usage": aira/basic_usage.md
      - "Connecting via SSH": aira/connecting_via_ssh.md
      - FAQ: aira/faq.md
    - "Agent Development":
      - "Robonomics Network":
        - "How It Works": agent_development/robonomics_network/how_it_works.md
        - "Contracts Deployment": agent_development/robonomics_network/contracts_deployment.md
        - "Become a Provider": agent_development/robonomics_network/become_a_provider.md
      - "Market Messages": agent_development/market_messages.md
      - "ROS API Reference":
        - "Robonomics Liability": agent_development/api/robonomics_liability.md
        - "Robonomics Liability Messages": agent_development/api/robonomics_liability_msgs.md
        - "Ethereum Common": agent_development/api/ethereum_common.md
        - "Ethereum Common Messages": agent_development/api/ethereum_common_msgs.md
        - "IPFS Common": agent_development/api/ipfs_common.md
        - "IPFS Common Messages": agent_development/api/ipfs_common_msgs.md
      - Examples: agent_development/examples.md
      - "Hardware Examples":
        - "Connect the Simplest CPS": agent_development/hardware_examples/connect_simple_cps.md
        - "Passing Dynamic Parameters": agent_development/hardware_examples/passing_dynamic_parameters.md
        - "Connect an Air Pollution Sensor": agent_development/hardware_examples/connect_sensor.md
    - "Robonomics-js": robonomics-js.md
    - Glossary: glossary.md
  - Contributing: contributing.md

theme:
  name: 'material'
  favicon: 'img/favicon.ico'
repo_url: 'https://github.com/airalab/robonomics-wiki'
repo_name: 'airalab/robonomics-wiki'
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
extra:
  social:
    - type: "github"
      link: "https://github.com/airalab/"
    - type: "twitter"
      link: "https://twitter.com/AIRA_Robonomics"

